// 主播
export const QUIZ_LIST_VISIBLE = 'QUIZ_LIST_VISIBLE'
export const QUIZ_NEW_VISIBLE = 'QUIZ_NEW_VISIBLE'
export const QUIZ_EDIT_VISIBLE = 'QUIZ_EDIT_VISIBLE'
export const QUIZ_INDEX = 'QUIZ_INDEX'
export const RESET_TAB = 'RESET_TAB'
// 用户
export const QUIZ_VISITOR_LIST = 'QUIZ_VISITOR_LIST'
export const QUIZ_VISITOR_LIST_SOCKET = 'QUIZ_VISITOR_LIST_SOCKET'